config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  namespace :api do
    get :find, to: "find#show", defaults: { format: :json }
  end
end

app/controllers/api/find_controller.rb
module Api
  class FindController < ApplicationController
    respond_to :json
    layout false

    def show
      render json: person_finder.result
    end

    private

    def person_finder
      @person_finder ||= ::PeopleFinder.new(params[:email], params[:name])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @persons = config[:persons].paginate(page: params[:page], per_page: 10)
  end

  private

  def config
    @config ||= YAML.load_file("#{Rails.root}/config/persons.yml").symbolize_keys!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Person Searcher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%#= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="page-header">
      <h1><%= link_to "Person Searcher", root_path %></h1>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/index.html.erb
<div class="row">
  <div class="col-md-12">

    <div class="row">
      <div class="col-md-6">
        <div class="well bs-component">
          <form role="form" action="<%= api_find_path %>">
            <fieldset>
              <legend>Search person</legend>
              <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Name</label>
                <input type="text" name="name" class="form-control" id="exampleInputPassword1" placeholder="Name">
              </div>
              <button type="submit" class="btn btn-default">Search</button>
            </fieldset>
          </form>
        </div>
      </div>
    </div>


    <h3>Listing persons</h3>

    <%= will_paginate(@persons) %>

    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Email</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @persons.each do |person| %>
          <tr>
            <td class="col-md-4"><%= person["email"] %></td>
            <td class="col-md-4"><%= person["name"] %></td>
            <td class="col-md-4"><%= link_to("Check", api_find_path(email: person["email"], name: person["name"])) %></td>
          </tr>
        <% end%>
      </tbody>
    </table>

    <%= will_paginate(@persons) %>
  </div>
</div>